events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # 1. Запросы авторизации -> auth_service
        location /api/login { proxy_pass http://auth_service:8002/login; }
        location /api/register { proxy_pass http://auth_service:8002/register; }
        location /api/auth/ { proxy_pass http://auth_service:8002/auth/; }
        location /api/verify-email { proxy_pass http://auth_service:8002/verify-email; }
        location /api/resend-code { proxy_pass http://auth_service:8002/resend-code; }

        # 2. Запросы заказов -> order_service
        location /api/orders { proxy_pass http://order_service:8005/orders; }
        location /api/ml/predict { proxy_pass http://order_service:8005/ml/predict; }

        # 3. Запросы аналитики -> analytics_service
        location /api/analytics { proxy_pass http://analytics_service:8006/analytics; }

        # 4. Профиль юзера -> user_service
        location /api/users/me { proxy_pass http://user_service:8003/users/me; }

        # 5. Админское управление юзерами
        location /api/users/ { proxy_pass http://analytics_service:8006/users/; }

        # 6. Всё остальное (интерфейс) -> frontend
        location / { proxy_pass http://frontend:3000; }
    }
}