apiVersion: v1
kind: ConfigMap
metadata:
  name: logistics-config
data:
  # Общие переменные
  NOTIFICATION_SERVICE_URL: "http://notification-service:8004"
  ML_SERVICE_URL: "http://ml-service:8001"
---
apiVersion: v1
kind: Secret
metadata:
  name: logistics-secret
type: Opaque
stringData:
  # Пароли и доступы (в K8s stringData сам кодирует в base64)
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "logistics_risk_db"
  DATABASE_URL: "postgresql://user:password@postgres-service:5432/logistics_risk_db"